---
title: "Adossement Crédit"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #storyboard: true
    #social: menu
    vertical_layout: fill
---
Visualisation
=====================================  

```{r setup, include=FALSE}
library(flexdashboard)
library(shinydashboard)
#Pour la mise en forme du markdown
if (!require(plotly)){install.packages("plotly")} ; library(plotly) # Pour le heatmap de la matrice de correlation
if (!require(tidyr)){install.packages("tidyr")} ; library(tidyr)
if (!require(leaflet)){install.packages("leaflet")} ; library(leaflet)
if (!require(qtlcharts)){install.packages("qtlcharts")} ; library(qtlcharts) # Pour la correlation des variables
if (!require(pander)){install.packages("pander")} ; library(pander) # pour bien afficher les extract de table
library(dplyr)
library(readr)
library(htmlTable)

setwd("C:/Users/X097430/Desktop/Script R")
matrice<-read.delim("credit.txt")
  matrice[is.na(matrice)] <- 0


sec_agg_region<-matrice %>% 
    group_by(reseau,DS_DGC,agence) %>%
    summarise(
      nb_client=sum(nb_client),
      nb_credit_conso=sum(nb_credit_conso)
    )%>%
  mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(taux_adosse))

```

Column {data-width=650}
-----------------------------------------------------------------------

### Taux d'assement par agence

```{r}
colors <- c('#3B4E32', '#56A902', '#F8F8FF','#75D701')

a<-sec_agg_region %>% 
    group_by(agence) %>%
summarise(
      nb_client=sum(nb_client),
      nb_credit_conso=sum(nb_credit_conso)
    )%>%
  mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(taux_adosse))
a$agence <- factor(a$agence, levels = unique(a$agence)[order(a$taux_adosse, decreasing = TRUE)])

plot_ly(a, x = ~agence, y = ~taux_adosse, type = 'bar', name = 'Nb_cc_non_contacte') %>%
      layout(yaxis = list(title = 'Pourcentage'),xaxis=list(tittle="Adossement crédit conso par agence"), barmode = 'bar')%>% 
  layout(title = "Adossement crédit conso par agence",
         xaxis = list(title = ""),
         yaxis = list(title = "Pourcentage"))%>% 
layout(plot_bgcolor='#e3dede') %>% 
layout(paper_bgcolor='#e3dede')
```

Column {data-width=350}
-----------------------------------------------------------------------

### Type de réseau

```{r}
a<-sec_agg_region %>% 
    group_by(reseau) %>%
    summarise(
      nb_client=sum(nb_client),
      nb_credit_conso=sum(nb_credit_conso)
    )%>%
  mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(taux_adosse))

colors <- c('#3B4E32', '#56A902', '#F8F8FF','#75D701')



plot_ly(a, labels = ~reseau, values = ~nb_credit_conso, type = 'pie',showlegend =F,marker = list(colors = colors,
                      line = list(color = '#FFFFFF', width = 1))
        ) %>%
  layout(title = "Taux d'adossement crédit par réseau",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))%>%
layout(plot_bgcolor='#e3dede') %>% 
layout(paper_bgcolor='#e3dede')


```

### Taux adoosement crédit conso par DS/DGC

```{r}
a<-sec_agg_region %>% 
    group_by(DS_DGC) %>%
    summarise(
      nb_client=sum(nb_client),
      nb_credit_conso=sum(nb_credit_conso)
    )%>%
  mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(taux_adosse))

a$DS_DGC <- factor(a$DS_DGC, levels = unique(a$DS_DGC)[order(a$taux_adosse, decreasing = TRUE)])

plot_ly(a, x = ~DS_DGC, y = ~taux_adosse, type = 'bar', name = 'Nb_cc_non_contacte') %>%
      layout(yaxis = list(title = 'Pourcentage'),xaxis=list(tittle="Adossement crédit conso par DS/DGC"), barmode = 'bar')%>% 
  layout(title = "Adossement crédit conso par DS/DGC",
         xaxis = list(title = ""),
         yaxis = list(title = "Pourcentage"))%>% 
layout(plot_bgcolor='#e3dede') %>% 
layout(paper_bgcolor='#e3dede')

```

Données Brutes
=====================================  

```{r echo=FALSE}

embed_data= function(x= matrice, filename= "file.csv", label= "Télécharger les données en CSV"){

  # Create encoded Base64 datastream 
  encode_data= function(x){
    write.csv2(x, "./file.csv")
    enc= sprintf('data:text/csv;base64,%s', openssl::base64_encode(paste0(readLines("./file.csv"), collapse="\n")) )
    unlink("./file.csv")
    return(enc)
  }

  # String result ready to be placed in rmarkdown
  paste0("<a download='", filename, "' href=", encode_data(x), ">", label, "</a>")

}
```

`r embed_data(matrice, filename="credit.csv")` 

```{r}
if (!require(pander)){install.packages("pander")} ; library(pander) # pour bien afficher les extract de table
pander(matrice[, 3:5])
#???pandoc.table(matrice[1:3, 1:5])
#htmlTable(matrice)
```



