---
title: "Score PEL MAUVE"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #storyboard: true
    #social: menu
    vertical_layout: fill
---
Visualisation
=====================================  

```{r setup, include=FALSE}
library(flexdashboard)
library(shinydashboard)
#Pour la mise en forme du markdown
if (!require(plotly)){install.packages("plotly")} ; library(plotly) # Pour le heatmap de la matrice de correlation
if (!require(tidyr)){install.packages("tidyr")} ; library(tidyr)
if (!require(leaflet)){install.packages("leaflet")} ; library(leaflet)
if (!require(qtlcharts)){install.packages("qtlcharts")} ; library(qtlcharts) # Pour la correlation des variables
if (!require(pander)){install.packages("pander")} ; library(pander) # pour bien afficher les extract de table
if (!require(googleVis)){install.packages("googleVis")} ; library(googleVis)
library(dplyr)
library(readr)
library(htmlTable)

setwd("C:/Users/X097430/Desktop/Script R/score_pel")
matrice<-read.csv("SCORE_PEL_MAUVE.csv",sep =";" )
  matrice[is.na(matrice)] <- 0
  matrice<-matrice%>%arrange(desc(IDCLI_CALCULE,AGE))
 matrice2<- matrice %>% distinct(IDCLI_CALCULE, .keep_all = TRUE)
 matrice2[is.na(matrice2)] <- 0


sec_agg_region<-matrice2 %>% 
    group_by(tranche_age) %>%
    summarise(
      nb_client=n_distinct(IDCLI_CALCULE),
      mean_age=round(mean(AGE)),
      mean_quintile=round(mean(quintile))
    )%>%
  arrange(desc(mean_quintile))%>%
  mutate(percentage=round(nb_client/sum(nb_client)*100))




```

Column {data-width=650}
-----------------------------------------------------------------------

### Moyenne des quintiles et moyenne des ages 

```{r}

plot_ly(data = sec_agg_region, x = ~mean_quintile, y = ~mean_age,size = ~percentage, mode = 'markers', color = ~tranche_age)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Type de réseau

```{r}
colors <- c('#3B4E32', '#56A902', '#F8F8FF','#75D701')

a<-matrice %>% 
    group_by(tranche_age) %>%
    summarise(
      nb_client=n_distinct(IDCLI_CALCULE),
      #nb_part=n_distinct(IDPART_CALCULE),
      mean_age=round(mean(AGE)),
      mean_quintile=round(mean(quintile))
    )%>%
 # mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(mean_quintile))
#a$tranche_age <- factor(a$tranche_age, levels = unique(a$tranche_age)[order(a$nb_client, decreasing = TRUE)])

plot_ly(a, x = ~tranche_age, y = ~nb_client, type = 'bar', name = 'Nombre de CC') %>%
      layout(yaxis = list(title = 'Nombre de CC'),xaxis=list(tittle="tranche d'age"), barmode = 'bar')%>% 
  layout(title = "Distribution des tranches d'age",
         xaxis = list(title = ""),
         yaxis = list(title = "Nombre de CC"))%>% 
layout(plot_bgcolor='#e3dede') %>% 
layout(paper_bgcolor='#e3dede')

```

### Taux adoosement crédit conso par DS/DGC

```{r}

a<-matrice2 %>% 
    group_by(LIBSECO) %>%
    summarise(
      nb_client=n_distinct(IDCLI_CALCULE),
      #nb_part=n_distinct(IDPART_CALCULE),
      mean_age=round(mean(AGE)),
      mean_quintile=round(mean(quintile))
    )%>%
 # mutate(taux_adosse=100*nb_credit_conso/nb_client)%>%
  arrange(desc(mean_quintile))
#a$tranche_age <- factor(a$tranche_age, levels = unique(a$tranche_age)[order(a$nb_client, decreasing = TRUE)])

#colors <- c('#3B4E32', '#56A902', '#F8F8FF','#75D701')



plot_ly(a, labels = ~LIBSECO, values = ~nb_client, type = 'pie',showlegend =F,marker = list(colors = colors,
                      line = list(color = '#FFFFFF', width = 1))
        ) %>%
  layout(title = "Distribution des semaco",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))%>%
layout(plot_bgcolor='#e3dede') %>% 
layout(paper_bgcolor='#e3dede')


```

Données Brutes
=====================================  

```{r echo=FALSE}

a<-matrice2 %>% 
    group_by(LIBSECO,LIBSSGMA,tranche_age,quintile) %>%
    summarise(
      nb_client=n_distinct(IDCLI_CALCULE)
    )%>%
  arrange(desc(nb_client))

embed_data= function(x= a, filename= "file.csv", label= "Télécharger les données en CSV"){

  # Create encoded Base64 datastream 
  encode_data= function(x){
    write.csv2(x, "./file.csv")
    enc= sprintf('data:text/csv;base64,%s', openssl::base64_encode(paste0(readLines("./file.csv"), collapse="\n")) )
    unlink("./file.csv")
    return(enc)
  }

  # String result ready to be placed in rmarkdown
  paste0("<a download='", filename, "' href=", encode_data(x), ">", label, "</a>")

}
```

`r embed_data(a, filename="score_pel.csv")` 

```{r}
if (!require(pander)){install.packages("pander")} ; library(pander) # pour bien afficher les extract de table
pander(a[, 1:5])
#???pandoc.table(matrice[1:3, 1:5])
#htmlTable(matrice)
```



